package main

import (
	"crypto/tls"
	"crypto/x509"
	"os"
	"path/filepath"
	"testing"
)

// CA 不存在 → 自动生成:私钥 0600、分发用 .crt 0644,且是一张真 CA 证书。
func TestCAAutoGenerated(t *testing.T) {
	path := filepath.Join(t.TempDir(), "ca_key")

	ca, err := loadOrCreateCA(path)
	if err != nil {
		t.Fatal(err)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("CA 私钥应已落盘: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Fatalf("CA 私钥权限应为 0600,实际 %o", perm)
	}
	crtInfo, err := os.Stat(ca.certPath)
	if err != nil {
		t.Fatalf("分发用 .crt 应已落盘: %v", err)
	}
	if perm := crtInfo.Mode().Perm(); perm != 0o644 {
		t.Fatalf(".crt 权限应为 0644,实际 %o", perm)
	}
	if !ca.cert.IsCA {
		t.Fatal("CA 证书的 IsCA 应为 true")
	}
	if ca.cert.KeyUsage&x509.KeyUsageCertSign == 0 {
		t.Fatal("CA 证书应有 CertSign 用途")
	}
}

// 重启复用同一把 CA —— 否则设备端已 pin 的信任会失效。
func TestCAReusedAcrossRestart(t *testing.T) {
	path := filepath.Join(t.TempDir(), "ca_key")

	ca1, err := loadOrCreateCA(path)
	if err != nil {
		t.Fatal(err)
	}
	ca2, err := loadOrCreateCA(path)
	if err != nil {
		t.Fatal(err)
	}
	if ca1.fingerprint != ca2.fingerprint {
		t.Fatalf("重启后 CA 指纹应不变: %s != %s", ca1.fingerprint, ca2.fingerprint)
	}
}

// .crt 被误删也能自愈(设备随时能重新取到信任锚)。
func TestCACertRegeneratedIfMissing(t *testing.T) {
	path := filepath.Join(t.TempDir(), "ca_key")

	ca1, err := loadOrCreateCA(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(ca1.certPath); err != nil {
		t.Fatal(err)
	}
	ca2, err := loadOrCreateCA(path)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(ca2.certPath); err != nil {
		t.Fatalf(".crt 应被重新写出: %v", err)
	}
	if ca1.fingerprint != ca2.fingerprint {
		t.Fatal("自愈不应换掉 CA")
	}
}

// 叶证书冒充 api.anthropic.com、由 CA 签发、且能通过标准链校验。
func TestLeafCertServesForgedHost(t *testing.T) {
	ca, err := loadOrCreateCA(filepath.Join(t.TempDir(), "ca_key"))
	if err != nil {
		t.Fatal(err)
	}
	conf, err := ca.serverTLSConfig()
	if err != nil {
		t.Fatal(err)
	}
	if conf.MinVersion < tls.VersionTLS12 {
		t.Fatalf("最低 TLS 版本应 >= 1.2,实际 %x", conf.MinVersion)
	}
	if len(conf.NextProtos) != 1 || conf.NextProtos[0] != "http/1.1" {
		t.Fatalf("ALPN 应只报 http/1.1(网关是 HTTP/1.1 server),实际 %v", conf.NextProtos)
	}

	leaf, err := x509.ParseCertificate(conf.Certificates[0].Certificate[0])
	if err != nil {
		t.Fatal(err)
	}
	pool := x509.NewCertPool()
	pool.AddCert(ca.cert)
	if _, err := leaf.Verify(x509.VerifyOptions{
		DNSName:   forgedHost,
		Roots:     pool,
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}); err != nil {
		t.Fatalf("叶证书应能以 %s 通过链校验: %v", forgedHost, err)
	}

	// 不该顺带冒充别的域名
	if _, err := leaf.Verify(x509.VerifyOptions{
		DNSName: "example.com", Roots: pool,
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}); err == nil {
		t.Fatal("叶证书不应对无关域名有效")
	}
}

// 每次启动重签叶证书,但信任锚(CA)不变 —— 设备端不受影响。
func TestLeafRegeneratedPerStart(t *testing.T) {
	ca, err := loadOrCreateCA(filepath.Join(t.TempDir(), "ca_key"))
	if err != nil {
		t.Fatal(err)
	}
	c1, err := ca.serverTLSConfig()
	if err != nil {
		t.Fatal(err)
	}
	c2, err := ca.serverTLSConfig()
	if err != nil {
		t.Fatal(err)
	}
	leaf1, _ := x509.ParseCertificate(c1.Certificates[0].Certificate[0])
	leaf2, _ := x509.ParseCertificate(c2.Certificates[0].Certificate[0])
	if leaf1.SerialNumber.Cmp(leaf2.SerialNumber) == 0 {
		t.Fatal("每次应签一张新的叶证书")
	}
}

// 损坏的 CA 文件要报错,不能静默换一把新的把设备全踢掉。
func TestBrokenCAFileErrors(t *testing.T) {
	path := filepath.Join(t.TempDir(), "ca_key")
	if err := os.WriteFile(path, []byte("not a pem file"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := loadOrCreateCA(path); err == nil {
		t.Fatal("损坏的 CA 文件应报错")
	}
}
